### ISSUE TITLE
Integrate all the apis to render results based on artists & songs

### ISSUE THREAD

**Issue by kanhairaval** [kanhairaval/cask-music-new#12]

**Comment by kirbyfridge** [comment]
- since there was a bug, we changed dropdown to song & video. now the user can look at top results from Spotify & YouTube easily. 
- when the user searches for a song, the Spotify link takes the user directly to the song whereas the YouTube link takes the user to a direct search of the corresponding song & artist name. 
- when the user searches for a video, the YouTube link takes the user directly to the video whereas the Spotify link takes the user to a direct search of their input in the search.
- because there was too many bugs & incorrect videos being pushed to the YouTube icon, this was the best course of action.
